### ISSUE TITLE
Label config file parsing error over URL

### ISSUE THREAD

**Issue by sohami** [julbme/gh-action-manage-label#1]
Hi,
I was trying to use this Github Action by providing the `labels.yml/labels.json` file using an https url. The action fails with below error. Tried reproducing it in a UT as well and I see the same error as below. Is this something known and have a workaround for it ?

Example run with failure and the workflow file: https://github.com/sohami/OpenSearch/actions/runs/9022590212/job/24792453065

```
Notice: processing source 'https://github.com/sohami/.github/tree/main/.github/config/labels.json'.
Exception in thread "main" java.util.concurrent.CompletionException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 7, column: 2]
	at me.julb.applications.github.actions.ManageLabelGitHubAction.execute(ManageLabelGitHubAction.java:136)
	at me.julb.Application.main(Application.java:43)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 7, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:23[9](https://github.com/sohami/OpenSearch/actions/runs/9022087354/job/24790804810#step:4:10)1)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2737)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:902)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at me.julb.applications.github.actions.ManageLabelGitHubAction.getInputLabels(ManageLabelGitHubAction.java:208)
	at me.julb.applications.github.actions.ManageLabelGitHubAction.execute(ManageLabelGitHubAction.java:[10](https://github.com/sohami/OpenSearch/actions/runs/9022087354/job/24790804810#step:4:11)4)
	... 1 more
```

**Comment by andrross** [comment]
@sohami The source you're trying to parse (https://github.com/sohami/.github/tree/main/.github/config/labels.json) is an HTML page. You need to give the raw URL in order for JSON to be returned: https://raw.githubusercontent.com/sohami/.github/main/.github/config/labels.json
